version: '3'
services:
    ilias:
        image: sturai/ilias:7.5-php7.4-apache
        container_name: ilias_ilias_1
        ports:
          - 8090:80
        links:
          - mysql
        environment:
          - ILIAS_AUTO_SETUP=1
          - ILIAS_DB_USER=root
          - ILIAS_DB_PASSWORD=example
          - ILIAS_ROOT_PASSWORD=root
          - ILIAS_INSTALL_ARGUMENTS=--no-plugins
        volumes:
          - ${ILIAS_LOCAL_ROOT}/Customizing/global/plugins/Services/Repository/RepositoryObject/MumieTask:/var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/MumieTask
          - ${ILIAS_LOCAL_ROOT}/Customizing/global/plugins/Services/EventHandling/EventHook/MumieTaskHook:/var/www/html/Customizing/global/plugins/Services/EventHandling/EventHook/MumieTaskHook
    mysql:
        image: mysql:5.7
        command: |
            --character-set-server=utf8
            --collation-server=utf8_general_ci
            --max-allowed-packet=16M
        environment:
          - MYSQL_ROOT_PASSWORD=example
          - MYSQL_DATABASE=ilias
